import 'package:flutter/material.dart';
import 'package:retro/features/create/create_replace_textures/create_replace_textures_viewmodel.dart';

// ignore: non_constant_identifier_names
Widget QuestionContent(CreateReplaceTexturesViewModel viewModel, BuildContext context) {
  final ThemeData theme = Theme.of(context);
  final TextTheme textTheme = theme.textTheme;
  
  return Column(
    mainAxisAlignment: MainAxisAlignment.center,
    children: [
      Text(
        "Do you already have a texture replacement folder?",
        style: textTheme.headline6,
      ),
      SizedBox(
        width: 500,
        child: Text(
          "If you have a folder generated by this tool with replacements, select Yes. If you don't have one, select No and we'll get you started with creating replacements.",
          style: textTheme.caption?.copyWith(color: Colors.grey),
          textAlign: TextAlign.center,
        )
      ),
      const SizedBox(height: 20),
      Row(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          ElevatedButton(
              onPressed: () {
                viewModel.onUpdateStep(CreateReplacementTexturesStep.selectFolder);
              },
              child: const Text("Yes")),
          const SizedBox(width: 20),
          ElevatedButton(
              onPressed: () {
                viewModel.onUpdateStep(CreateReplacementTexturesStep.selectOTR);
              },
              child: const Text("No")),
        ],
      )
    ],
  );
}
