// ignore: unused_import
import 'package:intl/intl.dart' as intl;
import 'app_localizations.dart';

// ignore_for_file: type=lint

/// The translations for English (`en`).
class AppLocalizationsEn extends AppLocalizations {
  AppLocalizationsEn([String locale = 'en']) : super(locale);

  @override
  String get appTitle => 'Retro';

  @override
  String get home_createOption => 'Create OTR / O2R';

  @override
  String get home_createOptionSubtitle => 'Create an OTR / O2R for SoH';

  @override
  String get home_inspectOption => 'Inspect OTR / O2R';

  @override
  String get home_inspectOptionSubtitle =>
      'Inspect the contents of an OTR / O2R';

  @override
  String get createSelectionScreen_title => 'Create Selection';

  @override
  String get createSelectionScreen_subtitle =>
      'Select the type of selection you want to create';

  @override
  String get createSelectionScreen_nonHdTex => 'Replace Textures';

  @override
  String get createSelectionScreen_customSequences => 'Custom Sequences';

  @override
  String get createSelectionScreen_custom => 'Custom';

  @override
  String get createReplaceTexturesScreen_Option => 'Replace Textures';

  @override
  String get createReplaceTexturesScreen_OptionDescription =>
      'Replace textures from an OTR / O2R with custom ones';

  @override
  String get questionContentView_mainQuestion =>
      'Do you already have a texture replacement folder?';

  @override
  String get questionContentView_mainText =>
      'If you have a folder generated by this tool with replacements, select Yes.\nIf you don\'t have one, select No and we\'ll get you started with creating replacements.';

  @override
  String get questionContentView_yes => 'Yes';

  @override
  String get questionContentView_no => 'No';

  @override
  String get otrContentView_otrPath => 'OTR / O2R Path';

  @override
  String get otrContentView_otrSelect => 'Select';

  @override
  String get otrContentView_details => 'Details';

  @override
  String get otrContentView_step1 =>
      '1. Select OTR / O2R that you want to replace textures from';

  @override
  String get otrContentView_step2 =>
      '2. We extract texture assets as PNG with correct folder structure';

  @override
  String get otrContentView_step3 =>
      '3. You replace the textures in that extraction folder';

  @override
  String get otrContentView_step4 =>
      '4. Run this flow again and present your extraction folder';

  @override
  String get otrContentView_step5 =>
      '5. We generate an OTR / O2R with the changed textures! 🚀';

  @override
  String get otrContentView_processing => 'Processing...';

  @override
  String get folderContentView_customTexturePath =>
      'Custom Texture Replacements Folder';

  @override
  String get folderContentView_prependAltToggle =>
      'Prepend `alt/`. This will allow players to toggle these assets on-the-fly in game.';

  @override
  String get folderContentView_compressToggle =>
      'Compress Files. This will reduce the size of the OTR / O2R.';

  @override
  String get folderContentView_selectButton => 'Select';

  @override
  String get folderContentView_stageTextures => 'Stage Textures';

  @override
  String get createCustomSequences_addCustomSequences => 'Add Custom Sequences';

  @override
  String get createCustomSequences_addCustomSequencesDescription =>
      'Select a folder with sequences and meta files';

  @override
  String get createCustomSequences_SequencesFolderPath =>
      'Sequences Folder Path';

  @override
  String get createCustomSequences_selectButton => 'Select';

  @override
  String get createCustomSequences_stageFiles => 'Stage Files';

  @override
  String get createFinishScreen_finish => 'Finish';

  @override
  String get createFinishScreen_finishSubtitle =>
      'Review your OTR / O2R details';

  @override
  String get createFinishScreen_generateOtr => 'Generate OTR / O2R';

  @override
  String get components_ephemeralBar_finalizeOtr => 'Finalize OTR / O2R ⚡️';

  @override
  String get createCustomScreen_title => 'Custom Directory';

  @override
  String get createCustomScreen_subtitle => 'Select directory to pack as .otr';

  @override
  String get createCustomScreen_labelPath => 'Path';

  @override
  String get createCustomScreen_selectButton => 'Select Directory';

  @override
  String get createCustomScreen_fileToInsert => 'Files to insert: ';

  @override
  String get createCustomScreen_stageFiles => 'Stage Files';

  @override
  String get inspectOtrScreen_inspectOtr => 'Inspect OTR / O2R';

  @override
  String get inspectOtrScreen_inspectOtrSubtitle =>
      'Inspect the contents of an OTR / O2R';

  @override
  String get inspectOtrScreen_noOtrSelected => 'No OTR / O2R Selected';

  @override
  String get inspectOtrScreen_selectButton => 'Select';

  @override
  String get inspectOtrScreen_search => 'Search';

  @override
  String get gameSelectionScreen_title => 'Game Specific Tools';

  @override
  String get gameSelectionScreen_subtitle =>
      'Select the game you want to create a selection for';

  @override
  String get gameSelectionScreenSoh_title => 'Ship of Harkinian';

  @override
  String get gameSelectionScreenSoh_subtitle =>
      'Select the tool you want to use';

  @override
  String get sohCreateDebugFontScreen_title => 'Debug Font Converter';

  @override
  String get sohCreateDebugFontScreen_subtitle =>
      'Convert and generate fonts for the soh map selector';

  @override
  String get gameSelectionScreen2Ship_title => '2 Ship 2 Harkinian';

  @override
  String get gameSelectionScreen2Ship_subtitle =>
      'Select the tool you want to use';

  @override
  String get gameSelection2ShipComingSoon_text =>
      '2 Ship 2 Harkinian Tools are coming soon!';

  @override
  String get extractModsWarning_part1 => 'Extracting existing mods';

  @override
  String get extractModsWarning_part2 => 'might not work properly.';
}
